// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:810636ef-6bd1-401b-b1e2-9913b8327033",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_xpzK6jJBL",
    "aws_user_pools_web_client_id": "4t6lem37tkgfhqt57gc3i1b3mv",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://gwtjkmrgejd63awaju7y5plrre.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
